### ISSUE TITLE
Issue with cheerio

### ISSUE THREAD

**Issue by Cryptoc1** [dzt/sScout#3]
There's is a bug with the implementation of cheerio that results in an uncaught typeerror. Screenshot included (note that the topbar bug was fixed in [pull request #2](https://github.com/dzt/sScout/pull/2)

![screen shot 2016-09-06 at 10 14 01 pm](https://cloud.githubusercontent.com/assets/6041110/18297783/7297e690-7481-11e6-9582-9e4b62bef8a9.png)

**Comment by dzt** [comment]
Ya I gotta remove that cheerio stuff because it's no longer in use since I have the supreme-api module running those important tasks for the sanity of my mind I'll fix it asap.
